server {
  listen 80;
  server_name _;

  client_max_body_size 100M;

  location /health { return 200 "ok\n"; }

  location / {
    proxy_pass http://app:5010;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    auth_basic           "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;
  }
}
