# app/routes/pdf_reports.py

from __future__ import annotations

import csv
import io
import json
from pathlib import Path

from flask import Blueprint, abort, send_file
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

pdf_reports_bp = Blueprint("pdf_reports", __name__)

PROJECT_ROOT = Path(__file__).resolve().parents[2]

JOBS_ROOT = PROJECT_ROOT / "uploads" / "jobs"


def _job_dir(job_id: str) -> Path:

    return JOBS_ROOT / job_id


def _meta_path(job_id: str) -> Path:

    return _job_dir(job_id) / "meta.json"


def _issues_path(job_id: str) -> Path:

    return _job_dir(job_id) / "issues.csv"


def _load_meta(job_id: str) -> dict:

    path = _meta_path(job_id)

    if not path.exists():
        return {}

    try:
        return json.loads(path.read_text(encoding="utf-8"))

    except Exception:
        return {}


def _load_issues(job_id: str) -> list[dict]:

    path = _issues_path(job_id)

    if not path.exists():
        return []

    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)

        return list(reader)


def _draw_line(pdf: canvas.Canvas, text: str, x: float, y: float, font="Helvetica", size=10):

    pdf.setFont(font, size)

    pdf.drawString(x, y, text)


@pdf_reports_bp.get("/qa/<job_id>")
def qa_pdf(job_id: str):

    job_path = _job_dir(job_id)

    if not job_path.exists():
        abort(404)

    meta = _load_meta(job_id)

    issues = _load_issues(job_id)

    buffer = io.BytesIO()

    pdf = canvas.Canvas(buffer, pagesize=A4)

    width, height = A4

    left = 18 * mm

    top = height - 18 * mm

    line_gap = 6 * mm

    y = top

    # Title

    _draw_line(pdf, "SpanCore EW — QA Report", left, y, font="Helvetica-Bold", size=16)

    y -= 10 * mm

    # Job summary

    _draw_line(pdf, f"Job ID: {job_id}", left, y, font="Helvetica-Bold", size=11)

    y -= line_gap

    _draw_line(pdf, f"Status: {meta.get('status', 'unknown')}", left, y)

    y -= line_gap

    _draw_line(pdf, f"Rulepack: {meta.get('rulepack_id', 'SPEN_11kV')}", left, y)

    y -= line_gap

    _draw_line(pdf, f"Auto-normalized: {meta.get('auto_normalized', False)}", left, y)

    y -= line_gap

    _draw_line(pdf, f"Pole count: {meta.get('pole_count', 0)}", left, y)

    y -= line_gap

    _draw_line(pdf, f"Issue count: {meta.get('issue_count', 0)}", left, y)

    y -= 10 * mm

    _draw_line(pdf, "Issues", left, y, font="Helvetica-Bold", size=12)

    y -= 8 * mm

    if not issues:
        _draw_line(pdf, "No issues.csv found for this job, or no issues were recorded.", left, y)

        y -= line_gap

    else:
        max_rows = 20

        for idx, issue in enumerate(issues[:max_rows], start=1):
            issue_text = str(issue.get("Issue", "Unknown issue")).strip()

            row_text = str(issue.get("Row", "")).strip()

            _draw_line(pdf, f"{idx}. {issue_text}", left, y)

            y -= line_gap

            if row_text:
                trimmed = row_text[:120]

                _draw_line(pdf, f"   Row: {trimmed}", left, y, size=9)

                y -= line_gap

            if y < 25 * mm:
                pdf.showPage()

                y = top

                _draw_line(
                    pdf,
                    "SpanCore EW — QA Report (continued)",
                    left,
                    y,
                    font="Helvetica-Bold",
                    size=14,
                )

                y -= 10 * mm

        if len(issues) > max_rows:
            _draw_line(
                pdf, f"... {len(issues) - max_rows} more issue(s) not shown in this PDF.", left, y
            )

            y -= line_gap

    y -= 6 * mm

    _draw_line(pdf, "Generated by SpanCore local MVP.", left, y, size=9)

    pdf.showPage()

    pdf.save()

    buffer.seek(0)

    return send_file(
        buffer,
        mimetype="application/pdf",
        as_attachment=False,
        download_name=f"{job_id}_qa_report.pdf",
    )
