"""PDF survey export."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from gridflow.exports.excel_exporter import ExportBundle, SurveyExportCollector


class SurveyPDFExporter:
    """Export survey evidence to a summary PDF."""

    def __init__(self) -> None:
        self._collector = SurveyExportCollector()

    def export(
        self, survey_root: str | Path, trace_path: str | Path, output_path: str | Path
    ) -> ExportBundle:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            PageBreak,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
        )

        bundle = self._collector.collect(survey_root, trace_path)
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            leftMargin=15 * mm,
            rightMargin=15 * mm,
            topMargin=18 * mm,
            bottomMargin=18 * mm,
        )
        styles = getSampleStyleSheet()
        title_style = styles["Title"]
        title_style.fontName = "Helvetica-Bold"
        title_style.fontSize = 20
        title_style.leading = 24
        body_style = styles["BodyText"]
        small_style = ParagraphStyle(
            "GridFlowSmall",
            parent=body_style,
            fontSize=9,
            leading=11,
        )

        story: list[Any] = [
            Paragraph("GridFlow Survey Evidence Report", title_style),
            Spacer(1, 6 * mm),
            Paragraph(f"<b>Survey:</b> {bundle.survey_name}", body_style),
            Paragraph(f"<b>Export date:</b> {bundle.export_timestamp}", body_style),
            Paragraph("<b>Generated by:</b> Unitas GridFlow", body_style),
            Spacer(1, 6 * mm),
            self._summary_table(bundle),
            Spacer(1, 8 * mm),
            Paragraph(
                f"<b>Trace source:</b> {bundle.trace_source_file or 'Not available'}",
                small_style,
            ),
            PageBreak(),
            Paragraph("Pole Detail Summary", styles["Heading2"]),
            Spacer(1, 4 * mm),
            self._pole_table(bundle),
        ]

        doc.build(story, canvasmaker=_NumberedCanvas)
        return bundle

    def _summary_table(self, bundle: ExportBundle):
        from reportlab.lib import colors
        from reportlab.lib.units import mm
        from reportlab.platypus import Table, TableStyle

        rows = [
            ["Metric", "Value"],
            ["Total poles", str(bundle.total_poles)],
            ["Ready", str(bundle.ready_count)],
            ["Review required", str(bundle.review_required_count)],
            ["Not ready", str(bundle.not_ready_count)],
            ["Total photos", str(bundle.total_photos)],
            ["Total conflicts", str(bundle.total_conflicts)],
        ]
        table = Table(rows, colWidths=[70 * mm, 45 * mm], repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#d9eaf7")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, colors.HexColor("#f8fafc")],
                    ),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        return table

    def _pole_table(self, bundle: ExportBundle):
        from reportlab.lib import colors
        from reportlab.lib.units import mm
        from reportlab.platypus import Table, TableStyle

        rows: list[list[str]] = [
            [
                "Pole",
                "Support",
                "Status",
                "Confidence",
                "Photos",
                "Conflicts",
                "Blockers",
            ]
        ]
        for row in bundle.pole_rows:
            rows.append(
                [
                    str(row.get("pole_folder") or ""),
                    str(row.get("support_no") or ""),
                    str(row.get("readiness_status") or ""),
                    str(row.get("linking_confidence") or ""),
                    str(row.get("photo_count") or 0),
                    str(row.get("conflict_count") or 0),
                    str(row.get("readiness_blockers") or "—"),
                ]
            )

        table = Table(
            rows,
            colWidths=[30 * mm, 22 * mm, 24 * mm, 24 * mm, 16 * mm, 18 * mm, 56 * mm],
            repeatRows=1,
        )
        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#d9eaf7")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("LEADING", (0, 0), (-1, -1), 10),
        ]
        for index, row in enumerate(bundle.pole_rows, start=1):
            status = str(row.get("readiness_status") or "")
            if status == "ready":
                fill = colors.HexColor("#dff2e1")
            elif status == "review_required":
                fill = colors.HexColor("#fff4d6")
            elif status == "not_ready":
                fill = colors.HexColor("#fadddd")
            else:
                fill = colors.HexColor("#e7e7e7")
            style_commands.append(("BACKGROUND", (0, index), (-1, index), fill))
        table.setStyle(TableStyle(style_commands))
        return table


class _NumberedCanvas:
    """Two-pass canvas for Page N of M footer."""

    def __init__(self, *args, **kwargs):
        from reportlab.pdfgen.canvas import Canvas

        self._canvas = Canvas(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def __getattr__(self, item):
        return getattr(self._canvas, item)

    def showPage(self):
        self._saved_page_states.append(dict(self._canvas.__dict__))
        self._canvas._startPage()

    def save(self):
        total_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self._canvas.__dict__.update(state)
            self._draw_page_count(total_pages)
            self._canvas.showPage()
        self._canvas.save()

    def _draw_page_count(self, page_count: int) -> None:
        page = self._canvas._pageNumber
        text = f"Unitas GridFlow | Survey Evidence Report | Page {page} of {page_count}"
        self._canvas.saveState()
        self._canvas.setFont("Helvetica", 8)
        self._canvas.setFillColorRGB(0.42, 0.45, 0.5)
        self._canvas.drawCentredString(297.5, 20, text)
        self._canvas.restoreState()
