"""Evidence provenance report for Stage 5A."""

from collections import Counter
from datetime import datetime
from typing import List

from gridflow.merge.models import MergedPole


class EvidenceProvenanceReporter:
    """Generate a data source audit trail for merged pole intelligence."""

    def generate(self, merged_poles: List[MergedPole]) -> str:
        """Return Markdown report generated only from merged pole records."""
        poles = list(merged_poles)
        lines = [
            "# Evidence Provenance Log - Job GridFlow Pipeline",
            "",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "**Purpose:** Data source audit trail for merged intelligence",
            "",
            "This log shows where each field came from: baseline, field survey, "
            "DNO records, or missing evidence.",
            "",
            "---",
            "",
        ]
        if not poles:
            lines.extend(["No merged poles were supplied.", "", self._summary([])])
            return "\n".join(lines)
        for pole in poles:
            lines.extend(self._pole_section(pole))
        lines.extend([self._summary(poles), "", "---"])
        lines.append(
            "*Report generated by GridFlow Stage 5A.2 for quality audits and evidence review*"
        )
        return "\n".join(lines)

    def _pole_section(self, pole: MergedPole) -> list[str]:
        status = "✅ design-ready" if pole.design_ready else "⚠️ design-blocked"
        return [
            f"## Pole {pole.support_no} - {status}",
            "",
            "### Core Identity",
            "",
            "| Field | Value | Source | Confidence | Notes |",
            "| --- | --- | --- | --- | --- |",
            f"| support_number | {pole.support_no} | Baseline / match register | {pole.match_confidence} | match type: {pole.match_type} |",
            f"| latitude | {self._fmt(pole.latitude)} | Baseline | HIGH | field GPS not used for authority |",
            f"| longitude | {self._fmt(pole.longitude)} | Baseline | HIGH | field GPS not used for authority |",
            f"| route_id | {self._fmt(pole.route_id)} | Baseline | MEDIUM | route context if supplied |",
            "",
            "### Physical Attributes",
            "",
            "| Field | Value | Source | Confidence | Notes |",
            "| --- | --- | --- | --- | --- |",
            f"| condition | {self._fmt(pole.condition_overall)} | Field survey | VARIABLE | from parsed notes where available |",
            f"| base condition | {self._fmt(pole.condition_base)} | Field survey | VARIABLE | visual observation only |",
            f"| top condition | {self._fmt(pole.condition_top)} | Field survey | VARIABLE | visual observation only |",
            "| pole_class | (missing) | DNO data required | N/A | not field-observable |",
            "",
            "### Electrical Attributes",
            "",
            "| Field | Value | Source | Confidence | Notes |",
            "| --- | --- | --- | --- | --- |",
            f"| voltage | {self._fmt(pole.baseline_voltage)} | Baseline if present | MEDIUM | DNO confirmation required for design |",
            "| conductor_spec | (missing) | DNO data required | N/A | not visible from field |",
            f"| equipment | {self._list(pole.equipment_observed)} | Field observation | VARIABLE | photo review recommended |",
            f"| warning_signs | {self._fmt(pole.warning_signs_present)} | Field observation | LOW-MEDIUM | not certified voltage data |",
            "",
            "### Mechanical Attributes",
            "",
            "| Field | Value | Source | Confidence | Notes |",
            "| --- | --- | --- | --- | --- |",
            f"| stay_present | {self._fmt(pole.stay_present)} | Field observation | VARIABLE | visible evidence only |",
            "| stay_type | (not specified) | Field survey gap | N/A | capture if relevant |",
            "| stay_direction | (not specified) | Field survey gap | N/A | capture if relevant |",
            "",
            "### Evidence Package",
            "",
            "**Field evidence captured:**",
            *[f"- {item}" for item in self._evidence_items(pole)],
            "",
            "**Missing evidence or data:**",
            *[f"- {item}" for item in self._missing_items(pole)],
            "",
            f"**Evidence quality:** {self._evidence_quality(pole)}",
            "",
            "---",
            "",
        ]

    def _summary(self, poles: list[MergedPole]) -> str:
        total = len(poles)
        quality = Counter(self._evidence_quality(p) for p in poles)
        notes = sum(1 for p in poles if p.notes_content)
        photos = sum(1 for p in poles if p.field_photo_count > 0)
        equipment = sum(1 for p in poles if p.equipment_observed)
        conductor_gap = sum(1 for p in poles if p.conductor_verification_required)
        pole_class_gap = sum(1 for p in poles if p.pole_class_verification_required)
        condition_gap = sum(1 for p in poles if not p.condition_overall)
        return "\n".join(
            [
                "## Summary Statistics",
                "",
                "### Data Source Breakdown",
                "",
                "| Data Source | Fields Contributed | Typical Confidence |",
                "| --- | --- | --- |",
                "| Baseline CSV | Support numbers, coordinates, voltage where present | HIGH for identity, MEDIUM for design context |",
                "| Field survey | Photos, notes, visible equipment, access observations | VARIABLE |",
                "| DNO records | Pending conductor specs, pole class, certified records | N/A until supplied |",
                "| Inference | Minimal report interpretation only | MEDIUM/LOW |",
                "",
                "### Common Evidence Gaps",
                "",
                f"1. **Conductor spec:** Missing for {conductor_gap}/{total} poles ({self._pct(conductor_gap, total)})",
                f"2. **Pole class:** Missing for {pole_class_gap}/{total} poles ({self._pct(pole_class_gap, total)})",
                f"3. **Structured condition:** Missing for {condition_gap}/{total} poles ({self._pct(condition_gap, total)})",
                "",
                "### Field Survey Quality Assessment",
                "",
                f"**Overall quality:** {self._overall_quality(quality, total)}",
                "",
                "**Strengths:**",
                f"- Photo evidence captured for {photos}/{total} poles",
                f"- Field notes present for {notes}/{total} poles",
                f"- Equipment observations parsed for {equipment}/{total} poles",
                "",
                "**Observation:** Field survey captured observable evidence. Missing data "
                "primarily consists of DNO engineering specifications that are not field-measurable.",
            ]
        )

    @staticmethod
    def _evidence_items(pole: MergedPole) -> list[str]:
        items = []
        if pole.field_photo_count:
            items.append(f"✅ {pole.field_photo_count} field photos")
        if pole.notes_content:
            items.append("✅ Field notes captured")
        if pole.latitude is not None and pole.longitude is not None:
            items.append("✅ Baseline coordinates present")
        if pole.equipment_observed:
            items.append("✅ Equipment observations parsed")
        return items or ["ℹ️ No field evidence fields populated in merged record"]

    @staticmethod
    def _missing_items(pole: MergedPole) -> list[str]:
        items = []
        if pole.conductor_verification_required:
            items.append("❌ Conductor specification requires DNO records")
        if pole.pole_class_verification_required:
            items.append("❌ Pole class requires DNO records")
        if pole.voltage_verification_required:
            items.append("⚠️ Certified voltage requires DNO confirmation")
        if not pole.condition_overall:
            items.append("ℹ️ Structured condition assessment not parsed")
        return items or ["✅ No additional gaps raised by merged record flags"]

    @staticmethod
    def _evidence_quality(pole: MergedPole) -> str:
        if pole.field_photo_count >= 3 and pole.notes_content:
            return "MEDIUM" if "NO_POLE_POPUP" in pole.special_flags else "HIGH"
        return "LOW"

    @staticmethod
    def _overall_quality(quality: Counter, total: int) -> str:
        if total == 0:
            return "NO DATA"
        return "HIGH" if quality["HIGH"] / total >= 0.8 else "MEDIUM/REVIEW REQUIRED"

    @staticmethod
    def _fmt(value) -> str:
        if value is None or value == "":
            return "(missing)"
        if isinstance(value, bool):
            return "Yes" if value else "No"
        return str(value)

    @staticmethod
    def _list(values: list[str]) -> str:
        return ", ".join(values) if values else "(missing)"

    @staticmethod
    def _pct(count: int, total: int) -> str:
        return "0%" if total == 0 else f"{count / total * 100:.0f}%"
