"""Verification flag breakdown report for Stage 5A."""

from collections import Counter
from datetime import datetime
from typing import Any, Callable, List

from gridflow.merge.models import MergedPole


class VerificationFlagsReporter:
    """Generate detailed verification flag analysis with standards references."""

    def generate(
        self, merged_poles: List[MergedPole], job_context: dict[str, Any] | None = None
    ) -> str:
        """Return Markdown report generated only from merged pole records."""
        ctx = job_context or {}
        job_id = ctx.get("job_id", "Unknown Job")
        baseline = ctx.get("baseline_file", "baseline.csv")
        field = ctx.get("field_folder", "field_evidence")
        timestamp = ctx.get("run_timestamp", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        poles = list(merged_poles)
        flagged = [p for p in poles if self._pole_flags(p)]
        active_specs = [(spec, self._affected(poles, spec)) for spec in self._specs()]
        active_specs = [(spec, affected) for spec, affected in active_specs if affected]

        lines = [
            f"# Verification Flags Breakdown - {job_id}",
            "",
            f"**Date:** {timestamp}",
            f"**Baseline:** {baseline}",
            f"**Field Evidence:** {field}",
            f"**Total poles with flags:** {len(flagged)}",
            f"**Unique flag types:** {len(active_specs)}",
            "",
            "---",
            "",
            "## Flag Definitions & Analysis",
            "",
        ]
        if not active_specs:
            lines.extend(["No verification flags were raised from the supplied records.", ""])
        for spec, affected in active_specs:
            lines.extend(self._flag_section(spec, affected))
        lines.extend(
            [
                "## Flag Combination Analysis",
                "",
                "**Poles with multiple flags:**",
                "",
                "| Support No | Flag Count | Flags Present |",
                "| --- | ---: | --- |",
            ]
        )
        combos = [(p, self._pole_flags(p)) for p in poles if len(self._pole_flags(p)) > 1]
        if combos:
            for pole, flags in combos:
                lines.append(f"| {pole.support_no} | {len(flags)} | {', '.join(flags)} |")
        else:
            lines.append("| None | 0 | No multi-flag poles |")
        lines.extend(["", self._priority_section(active_specs), "", "---"])
        lines.append(
            "*Report generated by GridFlow Stage 5A.2. Standards references: "
            "ENA G7/4, ESQCR 2002, ETR 132, BS EN 50341-1*"
        )
        return "\n".join(lines)

    @staticmethod
    def _specs() -> list[dict]:
        return [
            {
                "key": "conductor_spec_missing",
                "title": "⚠️ conductor_spec_missing",
                "severity": "CRITICAL",
                "test": lambda p: p.conductor_verification_required,
                "meaning": "Conductor specification is missing from available records.",
                "impact": (
                    "Span sag, loading, clearance, and PoleCAD design inputs require "
                    "conductor type, size, and material."
                ),
                "resolve": "Obtain conductor specification from DNO asset register.",
                "refs": "ENA G7/4 Section 3.2; BS EN 50341-1.",
            },
            {
                "key": "pole_class_missing",
                "title": "⚠️ pole_class_missing",
                "severity": "CRITICAL",
                "test": lambda p: p.pole_class_verification_required,
                "meaning": "Pole class or strength rating is missing from available records.",
                "impact": (
                    "Retention, replacement, stay design, and loading checks require "
                    "pole class or strength rating."
                ),
                "resolve": "Obtain pole class and load capacity from DNO asset records.",
                "refs": "ENA G7/4 Section 2.3; ETR 132.",
            },
            {
                "key": "voltage_conflict",
                "title": "❌ voltage_conflict",
                "severity": "HIGH (SAFETY RISK)",
                "test": lambda p: (
                    p.voltage_verification_required or "VOLTAGE_CONFLICT" in p.conflict_flags
                ),
                "meaning": "Voltage is missing, uncertain, or conflicts between sources.",
                "impact": (
                    "Voltage errors affect statutory clearances, safety controls, "
                    "and design assumptions."
                ),
                "resolve": "Confirm operating voltage and voltage boundaries with DNO records.",
                "refs": "ESQCR 2002 Regulation 19; ENA G7/4 Appendix A.",
            },
            {
                "key": "identity_confirmation_required",
                "title": "⚠️ identity_confirmation_required",
                "severity": "MEDIUM-HIGH",
                "test": lambda p: p.identity_verification_required,
                "meaning": "Support number match confidence is below HIGH.",
                "impact": "Identity errors can cause wrong-pole design and audit mismatch.",
                "resolve": "Cross-reference photos, DNO asset register, and coordinates.",
                "refs": "ENA P28 records and plans policy.",
            },
            {
                "key": "equipment_conflict",
                "title": "⚠️ equipment_conflict",
                "severity": "MEDIUM",
                "test": lambda p: "EQUIPMENT_CONFLICT" in p.conflict_flags,
                "meaning": "Equipment presence differs between baseline and field evidence.",
                "impact": "Equipment affects loading assumptions and site risk controls.",
                "resolve": "Confirm current equipment configuration and ratings with the DNO.",
                "refs": "ETR 132 and DNO equipment records.",
            },
            {
                "key": "condition_verification_required",
                "title": "ℹ️ condition_verification_required",
                "severity": "LOW-MEDIUM",
                "test": lambda p: p.condition_verification_required,
                "meaning": "Observed condition or defects need DNO review.",
                "impact": "Condition affects retention, safety planning, and replacement priority.",
                "resolve": "Request DNO condition inspection or current inspection outcome.",
                "refs": "ESQCR 2002 safety obligations; DNO condition grading process.",
            },
        ]

    @staticmethod
    def _affected(poles: list[MergedPole], spec: dict) -> list[MergedPole]:
        test: Callable[[MergedPole], bool] = spec["test"]
        return [p for p in poles if test(p)]

    @staticmethod
    def _flag_section(spec: dict, poles: list[MergedPole]) -> list[str]:
        return [
            f"### {spec['title']}",
            "",
            f"**Severity:** {spec['severity']}",
            f"**Count:** {len(poles)} poles affected",
            f"**Poles:** {', '.join(p.support_no for p in poles)}",
            "",
            "**What it means:**",
            spec["meaning"],
            "",
            "**Why it blocks design:**",
            spec["impact"],
            "",
            "**How to resolve:**",
            spec["resolve"],
            "",
            "**Standards reference:**",
            spec["refs"],
            "",
            "---",
            "",
        ]

    @classmethod
    def _pole_flags(cls, pole: MergedPole) -> list[str]:
        return [spec["key"] for spec in cls._specs() if spec["test"](pole)]

    @staticmethod
    def _priority_section(active_specs: list[tuple[dict, list[MergedPole]]]) -> str:
        counts = Counter({spec["key"]: len(poles) for spec, poles in active_specs})
        return "\n".join(
            [
                "## Recommended Resolution Priority",
                "",
                "**Priority 1 - CRITICAL:** conductor and pole class records.",
                f"- Missing conductor specification: {counts['conductor_spec_missing']} poles",
                f"- Missing pole class: {counts['pole_class_missing']} poles",
                "",
                "**Priority 2 - HIGH:** voltage and identity confirmation.",
                f"- Voltage conflicts or missing voltage: {counts['voltage_conflict']} poles",
                f"- Identity confirmation: {counts['identity_confirmation_required']} poles",
                "",
                "**Priority 3 - MEDIUM:** equipment and condition review.",
                f"- Equipment conflicts: {counts['equipment_conflict']} poles",
                f"- Condition verification: {counts['condition_verification_required']} poles",
            ]
        )
